CONFIG_SPI=y                   
CONFIG_INPUT=y                  
CONFIG_ZMK_MOUSE=y          
CONFIG_ZMK_EXT_POWER=y
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
